packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  bcrypt: true
  esbuild: false
  "@prisma/engines": true

  prisma: true
  sharp: true
  unrs-resolver: true
  node-base64: true
  msgpackr-extract: false

preferWorkspacePackages: true
