packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  bcrypt: true
  esbuild: false
  "@prisma/engines": true

  prisma: true
  sharp: true
  unrs-resolver: true
  node-base64: false
  msgpackr-extract: false
  '@google/genai': true
  protobufjs: true
  '@prisma/client': false
  '@parcel/watcher': true
  '@swc/core': true

preferWorkspacePackages: true
