import type { ConversationMessage } from "src/types/agent.types.js";

// runs before the tier is called
export function buildRoutingPrompt(
	latestMessage: string,
	conversationHistory: ConversationMessage[],
): string {
	const formattedHistory = conversationHistory
		.map((m) => `[${m.role.toUpperCase()}]: ${m.content}`)
		.join("\n");

	return `
You are a supervisor agent in a customer support AI pipeline.
Your job is to read the conversation and decide which tier should handle the latest customer message.

## Conversation History
${formattedHistory || "No previous messages — this is the first message."}

## Latest Customer Message
"${latestMessage}"

## Available Tiers
- tier0: Use when the question can be answered purely from the business knowledge base (FAQs, PDFs, documentation), OR when the message is a greeting, small talk, thanks, or has no specific support request — tier0 can respond conversationally.
- tier1: Use when answering requires fetching live business data (orders, accounts, subscriptions) via external APIs, combined with KB context.
- tier2: Use when the issue is complex, multi-step, or was not resolved by a previous tier.
- human: Use IMMEDIATELY when any of the following are true:
    * Customer explicitly asks for a human agent
    * Customer is extremely angry, distressed, or threatening
    * Situation is urgent or critical (legal, financial, safety)
    * The issue has already failed tier2

## Your Routing Rules
1. If the conversation history shows a tier already attempted and failed → escalate to the next tier, never retry the same tier
2. If no tiers have been attempted yet → start from the lowest capable tier (tier0 or tier1 depending on the message). Greetings, small talk, and messages with no specific request always start at tier0.
3. Human escalation bypasses all tiers — never route to a tier after deciding human

## Response Format
You must respond ONLY with a valid JSON object. No explanation, no markdown, no extra text.
"routingReason" must be a single short sentence with no line breaks or quotation marks.
Write "smallTalkReply" in the same language as the Latest Customer Message

{
  "routingDecision": "TIER0" | "TIER1" | "TIER2" | "HUMAN",
  "routingReason": "brief explanation of why you chose this tier",
  "smallTalkReply": "a short, friendly reply if the message is a greeting, thanks, or has no support request — otherwise null"
}

## Examples

Latest Customer Message: "hey"
{"routingDecision": "TIER0", "routingReason": "Greeting with no specific request", "smallTalkReply": "Hi there! How can I help you today?"}

Latest Customer Message: "thanks!"
{"routingDecision": "TIER0", "routingReason": "Customer expressing thanks, no further request", "smallTalkReply": "You're welcome! Let me know if there's anything else I can help with."}

Latest Customer Message: "where is my order #4521?"
{"routingDecision": "TIER1", "routingReason": "Requires live order data from an external API", "smallTalkReply": null}
`.trim();
}

// runs after the tier responds
export function buildReviewPrompt(
	latestMessage: string,
	tierResponse: string,
	tier: string,
): string {
	return `
You are a quality control supervisor in a customer support AI pipeline.
Your job is to review a tier's response before it reaches the customer and decide if it meets the quality bar.

## Original Customer Message
"${latestMessage}"

## Response Generated by ${tier.toUpperCase()}
"${tierResponse}"

## Quality Criteria — the response PASSES if ALL of these are true:
1. RELEVANT — directly addresses what the customer asked, does not answer a different question
2. COMPLETE — does not trail off, is not vague, gives the customer something actionable
3. CONFIDENT — does not say "I'm not sure" or "maybe" without providing real substance
4. ACCURATE TONE — professional, empathetic, not robotic or rude
5. NO OBVIOUS FABRICATION — does not contain suspicious specifics like invented phone numbers, 
made-up URLs, or contradicts itself within the same response. 
Do NOT reject a response simply because you cannot personally verify the facts because you don't have enough context to decide (this is the role of the tiers not the reviewer) — 
if the answer sounds plausible and consistent, treat it as passing this criterion.

## Your Review Rules
- If the response fails even ONE criterion → reject it
- Do not be lenient — a borderline response should be rejected, not approved
- A stub, placeholder, or empty response is always rejected

## Response Format
You must respond ONLY with a valid JSON object. No explanation, no markdown, no extra text.

{
  "reviewVerdict": "approved" | "rejected",
  "reviewReason": "brief explanation of your verdict"
}
`.trim();
}
