// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/* The Prisma CLI uses DIRECT_URL when you provide it because schema commands should use a direct database connection. 
The application uses DATABASE_URL through the Prisma pg adapter.*/

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: process.env.DATABASE_DIRECT_URL ?? process.env.DATABASE_URL ?? "",
	},
});
